FROM ghcr.io/linuxserver/baseimage-rdesktop-web:arm32v7-3.16

# set version label
ARG BUILD_DATE
ARG VERSION
ARG DARKTABLE_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# add local files
COPY /root /

RUN \
  echo "**** copy over not supported message ****" && \
  cp /defaults/autostart.armhf /defaults/autostart

# ports and volumes
EXPOSE 3000

VOLUME /config
